const mongoose = require('mongoose');

const ThreadSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true
  },
  mcode: {
    type: String,
    required: true
  },
  autogenerated: { //AKA DIRECTLY CONNECTED TO MODULES REVIEW PAGE
    type: Boolean,
    required: true
  }
});

module.exports = Thread = mongoose.model('thread', ThreadSchema);